version: "3.8"

services:
  php:
    image: php:8.1.2-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"

  db:
    image: postgres:9.6.24-alpine3.15

  adminer:
    image: adminer:4.8.1
