version: "3.8"

services:
  php:
    build: .
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"

  db:
    image: postgres:9.6.24-alpine3.15

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"
